# Introduction to Deep Learning with PyTorch

In [ ]:
import torch

In [ ]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))
print(features)
print(weights)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


Exercise: Calculate the output of the network with input features features, weights weights, and bias bias. Similar to Numpy, PyTorch has a torch.sum() function, as well as a .sum() method on tensors, for taking sums. Use the function activation defined above as the activation function.

In [ ]:
output=activation(torch.sum(features*weights)+bias)
output

tensor([[0.1595]])

Exercise: Calculate the output of our little network using matrix multiplication.

In [ ]:
features=features.view(5,1)
output=activation(torch.mm(weights,features)+bias)
output

tensor([[0.1595]])

In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

Exercise: Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.

In [ ]:
hidden=activation(torch.mm(features,W1)+B1)
output=activation(torch.mm(hidden,W2)+B2)
output

tensor([[0.3171]])

In [ ]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.67222868, 0.65339023, 0.90379652],
       [0.92379226, 0.34886848, 0.12975911],
       [0.58871283, 0.61270404, 0.73039271],
       [0.08059921, 0.22041439, 0.708564  ]])

In [ ]:
b = torch.from_numpy(a)
b

tensor([[0.6722, 0.6534, 0.9038],
        [0.9238, 0.3489, 0.1298],
        [0.5887, 0.6127, 0.7304],
        [0.0806, 0.2204, 0.7086]], dtype=torch.float64)

In [ ]:
b.numpy()

array([[0.67222868, 0.65339023, 0.90379652],
       [0.92379226, 0.34886848, 0.12975911],
       [0.58871283, 0.61270404, 0.73039271],
       [0.08059921, 0.22041439, 0.708564  ]])

In [ ]:
b.mul_(2)
a

array([[1.34445736, 1.30678047, 1.80759304],
       [1.84758453, 0.69773695, 0.25951823],
       [1.17742567, 1.22540807, 1.46078542],
       [0.16119842, 0.44082879, 1.41712801]])